---

# Install Microsot Visual Studio Code on Cento/RedHat

- name: install vscode repo
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: install vscode
  become: true
  yum:
    name: code
    state: latest